### ISSUE TITLE
"empty" results – why?

### ISSUE THREAD

**Issue by borbota** [k-monitor/parldata#15]
A testing user was unsure why the "empty" results are there (search term: "úny"):

![uny_kereses](https://user-images.githubusercontent.com/9154908/40574604-1892c218-60d5-11e8-9447-2b519a8b5c22.jpg)

The first empty result leads [here](http://www.parlament.hu/naplo35/292/2920223.htm), where this text does not appear at all. It is quite confusing. I suppose in this case "úny" appears somewhere in the title of the discussed law or alike, however, this remains hidden for the user. Maybe for such "empty" results we shall add an explanatory sentence?

**Comment by andraskalman** [comment]
"Úny" is found in the bill_title field and it is provided among the highlights:
```
"highlight" : {
          "bill_title" : [
            "Szükséges és gazdaságos-e új karsztvíz kimélõ létesítése az Esztergom, Dorog, Sárisáp, Csolnok, Tokod, Tokodaltáró, Tát, Máriahalom, Mogyorósbámya, Dág, <em>Úny</em>, Leányvár, Kesztölc, Piliscsév településeket ellátó vízbázison?"
          ]
        }
```
I think the bill_title field should be displayed with the highlights as well if there is a hit in that specifiec field. Plus if there is no text field among the highlights the first 150-300 chars of the text field should be displayed as well. @borbota @kantord what do you think about this solution? These changes should be introduced in the UI. I can check if ES supports the highlight alternative field for the text  (SOLR does) but I can't add the bill_title highlight to the displayed record from ES.

**Comment by kantord** [comment]
I agree, this should be introduced in the UI

**Comment by kantord** [comment]
see https://github.com/k-monitor/parliamentary_debates_open/issues/23

**Comment by borbota** [comment]
@andraskalman I agree, let's see how it looks like. Both the title and in case of no text highlight the first 150-300 chars of the text field.
